LET u=$TOK
IF (@TOKENID NEQ 0x00 AND @TOKENID NEQ u) OR (PREVSTATE(3) NEQ 0x00 AND PREVSTATE(3) NEQ u) THEN RETURN FALSE ENDIF
IF SIGNEDBY(PREVSTATE(0)) THEN
IF GETOUTADDR(@INPUT) EQ @ADDRESS THEN
RETURN SAMESTATE(0 1) AND SAMESTATE(3 5) AND SAMESTATE(7 8) AND STATE(2) GT 0 AND VERIFYOUT(@INPUT @ADDRESS @AMOUNT @TOKENID TRUE)
ENDIF
RETURN VERIFYOUT(@INPUT PREVSTATE(1) @AMOUNT @TOKENID FALSE)
ENDIF
IF @COINAGE GT $EXP THEN
RETURN VERIFYOUT(@INPUT PREVSTATE(1) @AMOUNT @TOKENID FALSE)
ENDIF
LET w=PREVSTATE(2)
LET r=0
IF @TOTOUT GT @INPUT+1 THEN
IF GETOUTADDR(@INPUT+1) EQ @ADDRESS THEN
LET r=GETOUTAMT(@INPUT+1)
ENDIF
ENDIF
IF r EQ 0 THEN
RETURN VERIFYOUT(@INPUT PREVSTATE(1) w PREVSTATE(3) FALSE)
ENDIF
RETURN r LT @AMOUNT AND r GTE PREVSTATE(8) AND VERIFYOUT(@INPUT+1 @ADDRESS r @TOKENID TRUE) AND SAMESTATE(0 1) AND SAMESTATE(3 5) AND SAMESTATE(7 8) AND STATE(2)*@AMOUNT GTE w*r AND STATE(2) LTE w AND GETOUTADDR(@INPUT) EQ PREVSTATE(1) AND GETOUTTOK(@INPUT) EQ PREVSTATE(3) AND GETOUTAMT(@INPUT)*@AMOUNT GTE w*(@AMOUNT-r)
